name: using secret keys as part of workflow

on: push

jobs: 
  build: 
    env: 
      SOME_JOB_ENV_VAR: "some alphanumeric value"
    runs-on: ubuntu-latest
    steps: 
      - name: Print some env vars
        run: echo "$SOME_JOB_ENV_VAR"
      - name: Log into aws with secret keys
        uses: aws-actions/configure-aws-credentials@v2
        with: 
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-2
          
